# Generated by Django 4.2 on 2023-12-16 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("modelos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="colores",
            options={"verbose_name_plural": "Colores"},
        ),
        migrations.AlterModelOptions(
            name="imagenes",
            options={"verbose_name_plural": "Imagenes"},
        ),
        migrations.AlterModelOptions(
            name="modelosvehiculos",
            options={"verbose_name_plural": "Modelos de Vehiculos"},
        ),
        migrations.AlterModelOptions(
            name="vehiculos",
            options={"verbose_name_plural": "Vehiculos"},
        ),
        migrations.RenameField(
            model_name="modelosvehiculos",
            old_name="id_vehiculo",
            new_name="vehiculo",
        ),
        migrations.RemoveField(
            model_name="vehiculos",
            name="imagenes",
        ),
        migrations.AddField(
            model_name="imagenes",
            name="vehiculo",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                to="modelos.vehiculos",
            ),
            preserve_default=False,
        ),
    ]
