# Generated by Django 4.2 on 2023-12-16 22:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelos", "0002_alter_colores_options_alter_imagenes_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiculos",
            name="fecha",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(4),
                    django.core.validators.MaxLengthValidator(4),
                ],
            ),
        ),
    ]
