# Generated by Django 4.2 on 2023-12-18 02:52

from django.db import migrations, models
import modelos.models


class Migration(migrations.Migration):

    dependencies = [
        ("modelos", "0003_alter_vehiculos_fecha"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiculos",
            name="fecha",
            field=models.IntegerField(
                null=True, validators=[modelos.models.Vehiculos.validar_cuatro_digitos]
            ),
        ),
    ]
