# Generated by Django 4.2 on 2023-12-20 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("modelos", "0004_alter_vehiculos_fecha"),
    ]

    operations = [
        migrations.RenameField(
            model_name="colores",
            old_name="id_colores",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="imagenes",
            old_name="id_imagen_modelo",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="modelosvehiculos",
            old_name="id_modelos_vehiculos",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="vehiculos",
            old_name="id_vehiculos",
            new_name="id",
        ),
    ]
